apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "daily-monetization.fullname" . }}
  labels:
    app: {{ template "daily-monetization.name" . }}
    chart: {{ template "daily-monetization.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  CAMPAIGNS_COUNT: {{ .Values.appConfig.campaignsCount | quote }}
  GCLOUD_PROJECT: {{ .Values.appConfig.gcloudProject }}

